version: "3"
services:
  redis-server:
    image: "redis:lattest"
    restart: "on-failure"
  flaskapp:
    build:
      context: "./app"
      dockerfile: "Dockerfile"
    image: "flaskapp:latest"
    ports:
      -"3001:80"
    depends_on:
      -"redis-server"
    restart: "on-failures"